/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WardleyStrategicPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/graph.ts
var StrategicGraph = class {
  constructor() {
    this.nodes = /* @__PURE__ */ new Map();
    this.edges = [];
    this.outIndex = /* @__PURE__ */ new Map();
    this.inIndex = /* @__PURE__ */ new Map();
  }
  addNode(id, node) {
    this.nodes.set(id, node);
    if (!this.outIndex.has(id))
      this.outIndex.set(id, []);
    if (!this.inIndex.has(id))
      this.inIndex.set(id, []);
  }
  getNode(id) {
    return this.nodes.get(id);
  }
  hasNode(id) {
    return this.nodes.has(id);
  }
  forEachNode(callback) {
    for (const [id, node] of this.nodes) {
      callback(id, node);
    }
  }
  nodeCount() {
    return this.nodes.size;
  }
  addEdge(source, target, field) {
    const edge = { source, target, field };
    this.edges.push(edge);
    if (!this.outIndex.has(source))
      this.outIndex.set(source, []);
    this.outIndex.get(source).push(edge);
    if (!this.inIndex.has(target))
      this.inIndex.set(target, []);
    this.inIndex.get(target).push(edge);
  }
  forEachEdge(callback) {
    for (const edge of this.edges) {
      callback(edge);
    }
  }
  getOutEdges(nodeId) {
    var _a;
    return (_a = this.outIndex.get(nodeId)) != null ? _a : [];
  }
  getInEdges(nodeId) {
    var _a;
    return (_a = this.inIndex.get(nodeId)) != null ? _a : [];
  }
  edgeCount() {
    return this.edges.length;
  }
  /** Returns all nodes that have strategic metadata. */
  getStrategicNodes() {
    const result = [];
    for (const node of this.nodes.values()) {
      if (node.strategic)
        result.push(node);
    }
    return result;
  }
  clear() {
    this.nodes.clear();
    this.edges = [];
    this.outIndex.clear();
    this.inIndex.clear();
  }
};

// src/scanner.ts
var import_obsidian = require("obsidian");

// src/types.ts
var STRATEGIC_TYPES = [
  "component",
  "user_need",
  "capability",
  "product",
  "service"
];
var EVOLUTION_STAGES = [
  "genesis",
  "custom",
  "product",
  "commodity"
];
var STRATEGIC_IMPORTANCE = [
  "critical",
  "important",
  "supporting",
  "optional"
];
var CONFIDENCE_LEVELS = [
  "high",
  "medium",
  "low"
];
var EDGE_TYPES = [
  "depends_on",
  "enables",
  "constrains",
  "evolves_to",
  "evolved_from"
];
var DEFAULT_VISUAL_SETTINGS = {
  font_size: 11,
  node_size: 12,
  node_colors: {
    critical: "var(--color-red)",
    important: "var(--color-orange)",
    supporting: "var(--color-blue)",
    optional: "var(--color-base-40)"
  },
  show_evolution_grid: true,
  show_axis_labels: true,
  edge_thickness: 2,
  component_spacing: 80,
  grid_color: "var(--text-muted)",
  grid_opacity: 0.5
};
var RELATIONSHIP_FIELDS = EDGE_TYPES;

// src/scanner.ts
var VaultScanner = class {
  constructor(app) {
    this.app = app;
  }
  scanVault() {
    const graph = new StrategicGraph();
    const warnings = [];
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file);
      const { strategic, problems } = this.extractStrategicMetadata(cache);
      if (problems.length > 0) {
        warnings.push({ path: file.path, problems });
      }
      if (strategic) {
        graph.addNode(file.path, {
          id: file.path,
          resolved: true,
          strategic
        });
      }
    }
    for (const file of files) {
      if (!graph.hasNode(file.path))
        continue;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!(cache == null ? void 0 : cache.frontmatterLinks))
        continue;
      for (const link of cache.frontmatterLinks) {
        const field = this.extractFieldName(link.key);
        if (!field || !RELATIONSHIP_FIELDS.includes(field))
          continue;
        const targetFile = this.app.metadataCache.getFirstLinkpathDest(
          link.link,
          file.path
        );
        if (targetFile instanceof import_obsidian.TFile) {
          if (!graph.hasNode(targetFile.path)) {
            const targetCache = this.app.metadataCache.getFileCache(targetFile);
            const { strategic: targetStrategic } = this.extractStrategicMetadata(targetCache);
            graph.addNode(targetFile.path, {
              id: targetFile.path,
              resolved: true,
              strategic: targetStrategic
            });
          }
          graph.addEdge(file.path, targetFile.path, field);
        }
      }
    }
    return { graph, warnings };
  }
  /**
   * Extract the field name from a frontmatterLinks key.
   * Keys look like "depends_on" or "depends_on.0" for array items.
   */
  extractFieldName(key) {
    const baseName = key.split(".")[0];
    if (RELATIONSHIP_FIELDS.includes(baseName)) {
      return baseName;
    }
    return null;
  }
  /**
   * Extract strategic metadata from a note's cached metadata.
   * Requires `wardley: true` in frontmatter to opt in.
   * Returns the extracted metadata and any problems found.
   */
  extractStrategicMetadata(cache) {
    const empty = { strategic: void 0, problems: [] };
    if (!(cache == null ? void 0 : cache.frontmatter))
      return empty;
    const fm = cache.frontmatter;
    if (fm.wardley !== true)
      return empty;
    const strategic = {};
    const problems = [];
    if (fm.type != null) {
      if (STRATEGIC_TYPES.includes(fm.type)) {
        strategic.type = fm.type;
      } else {
        problems.push(`Invalid type "${fm.type}". Expected: ${STRATEGIC_TYPES.join(", ")}`);
      }
    }
    if (fm.evolution_stage != null) {
      if (EVOLUTION_STAGES.includes(fm.evolution_stage)) {
        strategic.evolution_stage = fm.evolution_stage;
      } else {
        problems.push(`Invalid evolution_stage "${fm.evolution_stage}". Expected: ${EVOLUTION_STAGES.join(", ")}`);
      }
    }
    if (fm.strategic_importance != null) {
      if (STRATEGIC_IMPORTANCE.includes(fm.strategic_importance)) {
        strategic.strategic_importance = fm.strategic_importance;
      } else {
        problems.push(`Invalid strategic_importance "${fm.strategic_importance}". Expected: ${STRATEGIC_IMPORTANCE.join(", ")}`);
      }
    }
    if (fm.confidence_level != null) {
      if (CONFIDENCE_LEVELS.includes(fm.confidence_level)) {
        strategic.confidence_level = fm.confidence_level;
      } else {
        problems.push(`Invalid confidence_level "${fm.confidence_level}". Expected: ${CONFIDENCE_LEVELS.join(", ")}`);
      }
    }
    if (fm.evidence_sources) {
      strategic.evidence_sources = Array.isArray(fm.evidence_sources) ? fm.evidence_sources : [fm.evidence_sources];
    }
    if (fm.last_validated != null) {
      if (typeof fm.last_validated === "string" && /^\d{4}-\d{2}-\d{2}$/.test(fm.last_validated)) {
        strategic.last_validated = fm.last_validated;
      } else {
        problems.push(`Invalid last_validated "${fm.last_validated}". Expected: YYYY-MM-DD`);
      }
    }
    if (fm.strategic_maps) {
      strategic.strategic_maps = Array.isArray(fm.strategic_maps) ? fm.strategic_maps : [fm.strategic_maps];
    }
    if (Object.keys(strategic).length === 0) {
      problems.push("No valid strategic fields found. Note is skipped.");
      return { strategic: void 0, problems };
    }
    if (!strategic.evolution_stage) {
      problems.push("Missing evolution_stage. Component will appear but may be mispositioned.");
    }
    return { strategic, problems };
  }
};

// src/map-context.ts
var import_obsidian2 = require("obsidian");
var MapContextManager = class {
  constructor(app, graph) {
    this.cachedContexts = [];
    this.currentContext = null;
    this.app = app;
    this.graph = graph;
  }
  async detectMapContexts() {
    const contexts = [];
    const vaultContext = this.detectVaultContext();
    if (vaultContext)
      contexts.push(vaultContext);
    const folderContexts = await this.detectFolderContexts();
    contexts.push(...folderContexts);
    const membershipContexts = this.detectMembershipContexts();
    contexts.push(...membershipContexts);
    this.cachedContexts = contexts;
    return contexts;
  }
  detectVaultContext() {
    const strategicFiles = this.getStrategicFiles();
    if (strategicFiles.length === 0)
      return null;
    const hasFolderContexts = strategicFiles.some((file) => {
      if (!file.path.includes("/"))
        return false;
      const folderPath = file.path.substring(0, file.path.lastIndexOf("/"));
      return this.hasMapContextFile(folderPath);
    });
    if (!hasFolderContexts) {
      return {
        id: "vault",
        name: "Vault Strategic Map",
        scope: "vault",
        description: "Strategic map spanning entire vault"
      };
    }
    return null;
  }
  async detectFolderContexts() {
    const contexts = [];
    const allFiles = this.app.vault.getAllLoadedFiles();
    const folderPaths = /* @__PURE__ */ new Set();
    for (const file of allFiles) {
      if (file.path.includes("/") && this.app.vault.getAbstractFileByPath(file.path)) {
        const folderPath = file.path.substring(0, file.path.lastIndexOf("/"));
        folderPaths.add(folderPath);
      }
    }
    for (const folderPath of folderPaths) {
      const mapContextFile = this.app.vault.getAbstractFileByPath(
        `${folderPath}/Map-Context.md`
      );
      if (mapContextFile instanceof import_obsidian2.TFile) {
        const content = await this.app.vault.cachedRead(mapContextFile);
        const context = this.parseMapContextFile(content, folderPath);
        if (context)
          contexts.push(context);
      }
    }
    return contexts;
  }
  detectMembershipContexts() {
    const contexts = [];
    const mapMemberships = /* @__PURE__ */ new Map();
    this.graph.forEachNode((nodeId, attrs) => {
      var _a;
      if ((_a = attrs.strategic) == null ? void 0 : _a.strategic_maps) {
        for (const mapId of attrs.strategic.strategic_maps) {
          if (!mapMemberships.has(mapId))
            mapMemberships.set(mapId, []);
          mapMemberships.get(mapId).push(nodeId);
        }
      }
    });
    for (const [mapId, members] of mapMemberships) {
      contexts.push({
        id: mapId,
        name: mapId.replace(/[-_]/g, " ").replace(/\b\w/g, (l) => l.toUpperCase()),
        scope: "membership",
        description: `Strategic map with ${members.length} declared members`,
        includes: members
      });
    }
    return contexts;
  }
  parseMapContextFile(content, folderPath) {
    const titleMatch = content.match(/^#\s+(.+)$/m);
    const title = titleMatch ? titleMatch[1] : folderPath.split("/").pop() || "Untitled";
    const lines = content.split("\n");
    const headingIdx = lines.findIndex((l) => /^#\s+/.test(l));
    let description;
    if (headingIdx >= 0 && headingIdx + 2 < lines.length && lines[headingIdx + 1] === "") {
      const descLine = lines[headingIdx + 2];
      if (descLine && !descLine.startsWith("#")) {
        description = descLine.trim();
      }
    }
    return {
      id: folderPath,
      name: title,
      scope: "folder",
      description,
      includes: [folderPath]
    };
  }
  getStrategicFiles() {
    const strategicFiles = [];
    this.graph.forEachNode((nodeId, attrs) => {
      if (attrs.strategic && attrs.resolved) {
        const file = this.app.vault.getAbstractFileByPath(nodeId);
        if (file instanceof import_obsidian2.TFile)
          strategicFiles.push(file);
      }
    });
    return strategicFiles;
  }
  hasMapContextFile(folderPath) {
    const file = this.app.vault.getAbstractFileByPath(`${folderPath}/Map-Context.md`);
    return file instanceof import_obsidian2.TFile;
  }
  getCurrentMapContext() {
    return this.currentContext;
  }
  setCurrentMapContext(context) {
    this.currentContext = context;
  }
  getDefaultMapContext() {
    if (this.cachedContexts.length === 0)
      return null;
    const vaultContext = this.cachedContexts.find((ctx) => ctx.scope === "vault");
    if (vaultContext)
      return vaultContext;
    return this.cachedContexts[0];
  }
  getComponentsForMap(mapId) {
    const context = this.cachedContexts.find((ctx) => ctx.id === mapId);
    if (!context)
      return [];
    const components = [];
    this.graph.forEachNode((nodeId, attrs) => {
      var _a;
      if (!attrs.strategic)
        return;
      let includeInMap = false;
      switch (context.scope) {
        case "vault":
          includeInMap = attrs.resolved;
          break;
        case "folder":
          if (context.includes) {
            includeInMap = context.includes.some(
              (folder) => nodeId.startsWith(folder + "/")
            );
          }
          break;
        case "membership":
          includeInMap = ((_a = attrs.strategic.strategic_maps) == null ? void 0 : _a.includes(mapId)) || false;
          break;
      }
      if (includeInMap)
        components.push(nodeId);
    });
    return components;
  }
  refresh() {
    this.cachedContexts = [];
    this.currentContext = null;
  }
};

// src/views/map-view.ts
var import_obsidian3 = require("obsidian");

// src/positioner.ts
var WardleyPositioner = class {
  constructor(settings) {
    // Canvas dimensions (matching SVG viewBox)
    this.CANVAS_WIDTH = 800;
    this.CANVAS_HEIGHT = 600;
    this.MARGIN = 80;
    this.CONTENT_WIDTH = this.CANVAS_WIDTH - this.MARGIN * 2;
    this.CONTENT_HEIGHT = this.CANVAS_HEIGHT - this.MARGIN * 2;
    // Evolution stage band centers (centered within each quarter)
    this.STAGE_POSITIONS = {
      genesis: 0.125,
      custom: 0.375,
      product: 0.625,
      commodity: 0.875
    };
    this.settings = settings;
  }
  position(components, edges) {
    const positioned = [...components];
    this.positionByEvolution(positioned);
    this.positionByValueChain(positioned, edges);
    this.alignEvolutionPairs(positioned, edges);
    this.spreadOverlapping(positioned, edges);
    return positioned;
  }
  positionByEvolution(components) {
    var _a;
    for (const comp of components) {
      const stage = comp.strategic.evolution_stage || "custom";
      const bandCenter = (_a = this.STAGE_POSITIONS[stage]) != null ? _a : this.STAGE_POSITIONS.custom;
      comp.x = this.MARGIN + bandCenter * this.CONTENT_WIDTH;
    }
  }
  positionByValueChain(components, edges) {
    var _a;
    const depths = this.longestPathFromRoot(components, edges);
    const maxDepth = Math.max(...depths.values(), 0);
    for (const comp of components) {
      const depth = (_a = depths.get(comp.id)) != null ? _a : 0;
      if (maxDepth > 0) {
        comp.y = this.MARGIN + depth / (maxDepth + 1) * this.CONTENT_HEIGHT;
      } else {
        comp.y = this.MARGIN + this.CONTENT_HEIGHT / 2;
      }
    }
  }
  /**
   * Compute depth via longest path from root nodes (user needs / nodes with no incoming deps).
   * "A depends_on B" means B is deeper. "A enables B" means A is deeper.
   */
  longestPathFromRoot(components, edges) {
    var _a, _b, _c, _d, _e;
    const depths = /* @__PURE__ */ new Map();
    const children = /* @__PURE__ */ new Map();
    const hasParent = /* @__PURE__ */ new Set();
    for (const comp of components) {
      children.set(comp.id, []);
    }
    for (const edge of edges) {
      if (edge.type === "depends_on") {
        (_a = children.get(edge.source)) == null ? void 0 : _a.push(edge.target);
        hasParent.add(edge.target);
      } else if (edge.type === "enables") {
        (_b = children.get(edge.target)) == null ? void 0 : _b.push(edge.source);
        hasParent.add(edge.source);
      }
    }
    const roots = [];
    for (const comp of components) {
      const isUserNeed = comp.strategic.type === "user_need";
      if (isUserNeed || !hasParent.has(comp.id)) {
        roots.push(comp.id);
        depths.set(comp.id, 0);
      }
    }
    const queue = [...roots];
    while (queue.length > 0) {
      const current = queue.shift();
      const currentDepth = (_c = depths.get(current)) != null ? _c : 0;
      for (const child of (_d = children.get(current)) != null ? _d : []) {
        const prevDepth = (_e = depths.get(child)) != null ? _e : -1;
        const newDepth = currentDepth + 1;
        if (newDepth > prevDepth) {
          depths.set(child, newDepth);
          queue.push(child);
        }
      }
    }
    const stageDepths = {
      genesis: 1,
      custom: 2,
      product: 3,
      commodity: 4
    };
    const maxDepth = Math.max(...depths.values(), 0);
    for (const comp of components) {
      if (!depths.has(comp.id)) {
        const stage = comp.strategic.evolution_stage || "custom";
        const ratio = stageDepths[stage] / 5;
        depths.set(comp.id, Math.round(ratio * (maxDepth || 4)));
      }
    }
    return depths;
  }
  /** Evolved components share Y with their source. */
  alignEvolutionPairs(components, edges) {
    for (const edge of edges) {
      if (edge.type === "evolves_to") {
        const source = components.find((c) => c.id === edge.source);
        const target = components.find((c) => c.id === edge.target);
        if (source && target) {
          target.y = source.y;
        }
      } else if (edge.type === "evolved_from") {
        const source = components.find((c) => c.id === edge.source);
        const target = components.find((c) => c.id === edge.target);
        if (source && target) {
          source.y = target.y;
        }
      }
    }
  }
  /**
   * Spread components that share the same Y level and evolution stage.
   * Order by average neighbor X to reduce edge crossings.
   */
  spreadOverlapping(components, edges) {
    var _a, _b;
    const neighbors = /* @__PURE__ */ new Map();
    for (const comp of components) {
      neighbors.set(comp.id, []);
    }
    for (const edge of edges) {
      (_a = neighbors.get(edge.source)) == null ? void 0 : _a.push(edge.target);
      (_b = neighbors.get(edge.target)) == null ? void 0 : _b.push(edge.source);
    }
    const groups = /* @__PURE__ */ new Map();
    for (const comp of components) {
      const stage = comp.strategic.evolution_stage || "custom";
      const key = `${Math.round(comp.y)}_${stage}`;
      if (!groups.has(key))
        groups.set(key, []);
      groups.get(key).push(comp);
    }
    const compById = new Map(components.map((c) => [c.id, c]));
    for (const [, group] of groups) {
      if (group.length <= 1)
        continue;
      const baseX = group[0].x;
      group.sort((a, b) => {
        const avgA = this.averageNeighborX(a.id, neighbors, compById);
        const avgB = this.averageNeighborX(b.id, neighbors, compById);
        return avgA - avgB;
      });
      const spacing = this.settings.component_spacing;
      const baseSpread = Math.min(this.CONTENT_WIDTH * 0.15, (group.length - 1) * spacing);
      group.forEach((comp, index) => {
        const offset = (index - (group.length - 1) / 2) * (baseSpread / Math.max(group.length - 1, 1));
        comp.x = Math.max(this.MARGIN, Math.min(this.CANVAS_WIDTH - this.MARGIN, baseX + offset));
      });
    }
  }
  averageNeighborX(id, neighbors, compById) {
    var _a, _b, _c;
    const neighIds = (_a = neighbors.get(id)) != null ? _a : [];
    let sum = 0;
    let count = 0;
    for (const nid of neighIds) {
      const nc = compById.get(nid);
      if (nc) {
        sum += nc.x;
        count++;
      }
    }
    return count > 0 ? sum / count : (_c = (_b = compById.get(id)) == null ? void 0 : _b.x) != null ? _c : 400;
  }
};

// src/renderer.ts
var WardleyMapRenderer = class {
  constructor(container, graph, contextManager, settings, onComponentClick) {
    this.svg = null;
    this.components = [];
    this.edges = [];
    this.container = container;
    this.graph = graph;
    this.contextManager = contextManager;
    this.settings = settings;
    this.onComponentClick = onComponentClick;
    this.positioner = new WardleyPositioner(settings);
  }
  render(mapId) {
    this.clearCanvas();
    this.loadComponents(mapId);
    this.loadEdges();
    this.positionComponents();
    this.createSVG();
    this.renderAxes();
    this.renderEdges();
    this.renderComponents();
  }
  clearCanvas() {
    this.container.empty();
    this.svg = null;
    this.components = [];
    this.edges = [];
  }
  loadComponents(mapId) {
    const componentIds = this.contextManager.getComponentsForMap(mapId);
    this.components = [];
    for (const id of componentIds) {
      const node = this.graph.getNode(id);
      if (!(node == null ? void 0 : node.strategic))
        continue;
      this.components.push({
        id,
        name: this.getDisplayName(id),
        strategic: node.strategic,
        x: 0,
        y: 0
      });
    }
  }
  loadEdges() {
    this.edges = [];
    const componentIds = new Set(this.components.map((c) => c.id));
    this.graph.forEachEdge((edge) => {
      if (componentIds.has(edge.source) && componentIds.has(edge.target)) {
        this.edges.push({
          source: edge.source,
          target: edge.target,
          type: edge.field
        });
      }
    });
  }
  positionComponents() {
    this.components = this.positioner.position(this.components, this.edges);
  }
  createSVG() {
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("width", "100%");
    svg.setAttribute("height", "100%");
    svg.setAttribute("viewBox", "0 0 800 600");
    svg.style.width = "100%";
    svg.style.height = "100%";
    const defs = document.createElementNS("http://www.w3.org/2000/svg", "defs");
    const evolutionMarker = document.createElementNS("http://www.w3.org/2000/svg", "marker");
    evolutionMarker.setAttribute("id", "evolution-arrow");
    evolutionMarker.setAttribute("markerWidth", "10");
    evolutionMarker.setAttribute("markerHeight", "10");
    evolutionMarker.setAttribute("refX", "8");
    evolutionMarker.setAttribute("refY", "3");
    evolutionMarker.setAttribute("orient", "auto");
    evolutionMarker.setAttribute("markerUnits", "strokeWidth");
    const arrowPath = document.createElementNS("http://www.w3.org/2000/svg", "path");
    arrowPath.setAttribute("d", "M0,0 L0,6 L9,3 z");
    arrowPath.setAttribute("fill", "var(--color-purple)");
    evolutionMarker.appendChild(arrowPath);
    defs.appendChild(evolutionMarker);
    svg.appendChild(defs);
    this.container.appendChild(svg);
    this.svg = svg;
  }
  renderAxes() {
    if (!this.svg)
      return;
    const axesGroup = document.createElementNS("http://www.w3.org/2000/svg", "g");
    axesGroup.setAttribute("class", "wardley-axes");
    const yAxis = this.createLine(80, 50, 80, 550, "var(--text-muted)", 2);
    axesGroup.appendChild(yAxis);
    const xAxis = this.createLine(80, 550, 750, 550, "var(--text-muted)", 2);
    axesGroup.appendChild(xAxis);
    if (this.settings.show_axis_labels) {
      const yLabel = this.createText(50, 300, "Value Chain", "var(--text-muted)", 14);
      yLabel.setAttribute("transform", "rotate(-90, 50, 300)");
      axesGroup.appendChild(yLabel);
      const xLabel = this.createText(415, 590, "Evolution", "var(--text-muted)", 14);
      axesGroup.appendChild(xLabel);
    }
    const stages = ["Genesis", "Custom", "Product", "Commodity"];
    const stageCenters = [0.125, 0.375, 0.625, 0.875];
    for (let i = 0; i < stages.length; i++) {
      const x = 80 + stageCenters[i] * 640;
      if (this.settings.show_evolution_grid) {
        const gridLine = this.createLine(
          x,
          50,
          x,
          550,
          this.settings.grid_color,
          1,
          "2,3"
        );
        gridLine.setAttribute("opacity", this.settings.grid_opacity.toString());
        axesGroup.appendChild(gridLine);
      }
      const tick = this.createLine(x, 545, x, 555, "var(--text-muted)", 1);
      axesGroup.appendChild(tick);
      const label = this.createText(x, 575, stages[i], "var(--text-muted)", 12);
      axesGroup.appendChild(label);
    }
    this.svg.appendChild(axesGroup);
  }
  renderEdges() {
    if (!this.svg)
      return;
    const edgesGroup = document.createElementNS("http://www.w3.org/2000/svg", "g");
    edgesGroup.setAttribute("class", "wardley-edges");
    for (const edge of this.edges) {
      const source = this.components.find((c) => c.id === edge.source);
      const target = this.components.find((c) => c.id === edge.target);
      if (!source || !target)
        continue;
      const radius = this.settings.node_size;
      const { x1, y1, x2, y2 } = this.clipLineToCircles(
        source.x,
        source.y,
        target.x,
        target.y,
        radius
      );
      const line = this.createLine(
        x1,
        y1,
        x2,
        y2,
        this.getEdgeColor(edge.type),
        this.settings.edge_thickness,
        this.getEdgeDash(edge.type)
      );
      if (edge.type === "evolves_to") {
        line.setAttribute("marker-end", "url(#evolution-arrow)");
      }
      edgesGroup.appendChild(line);
    }
    this.svg.appendChild(edgesGroup);
  }
  renderComponents() {
    if (!this.svg)
      return;
    const componentsGroup = document.createElementNS("http://www.w3.org/2000/svg", "g");
    componentsGroup.setAttribute("class", "wardley-components");
    for (const comp of this.components) {
      const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
      circle.setAttribute("cx", comp.x.toString());
      circle.setAttribute("cy", comp.y.toString());
      circle.setAttribute("r", this.settings.node_size.toString());
      circle.setAttribute("fill", this.getComponentColor(comp));
      circle.setAttribute("stroke", "var(--text-normal)");
      circle.setAttribute("stroke-width", "2");
      circle.setAttribute("class", "wardley-component");
      circle.addEventListener("click", () => this.onComponentClick(comp.id));
      const title = document.createElementNS("http://www.w3.org/2000/svg", "title");
      title.textContent = [
        comp.name,
        `Type: ${comp.strategic.type || "unknown"}`,
        `Evolution: ${comp.strategic.evolution_stage || "unknown"}`,
        `Importance: ${comp.strategic.strategic_importance || "unknown"}`
      ].join("\n");
      circle.appendChild(title);
      componentsGroup.appendChild(circle);
      const text = this.createText(
        comp.x,
        comp.y + this.settings.node_size + 13,
        comp.name,
        "var(--text-normal)",
        this.settings.font_size
      );
      text.setAttribute("class", "wardley-label");
      componentsGroup.appendChild(text);
    }
    this.svg.appendChild(componentsGroup);
  }
  // --- Helpers ---
  getDisplayName(path) {
    var _a;
    return ((_a = path.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) || path;
  }
  getComponentColor(comp) {
    const importance = comp.strategic.strategic_importance || "supporting";
    return this.settings.node_colors[importance] || this.settings.node_colors.supporting;
  }
  getEdgeColor(type) {
    const colorMap = {
      depends_on: "var(--color-blue)",
      enables: "var(--color-green)",
      constrains: "var(--color-red)",
      evolves_to: "var(--color-purple)",
      evolved_from: "var(--color-purple)"
    };
    return colorMap[type] || "var(--text-muted)";
  }
  getEdgeDash(type) {
    if (type === "constrains")
      return "5,5";
    if (type === "evolves_to" || type === "evolved_from")
      return "3,3";
    return "";
  }
  clipLineToCircles(sx, sy, tx, ty, radius) {
    const dx = tx - sx;
    const dy = ty - sy;
    const dist = Math.sqrt(dx * dx + dy * dy);
    if (dist <= radius * 2)
      return { x1: sx, y1: sy, x2: tx, y2: ty };
    const ux = dx / dist;
    const uy = dy / dist;
    return {
      x1: sx + ux * radius,
      y1: sy + uy * radius,
      x2: tx - ux * radius,
      y2: ty - uy * radius
    };
  }
  createLine(x1, y1, x2, y2, stroke, strokeWidth, dashArray) {
    const line = document.createElementNS("http://www.w3.org/2000/svg", "line");
    line.setAttribute("x1", x1.toString());
    line.setAttribute("y1", y1.toString());
    line.setAttribute("x2", x2.toString());
    line.setAttribute("y2", y2.toString());
    line.setAttribute("stroke", stroke);
    line.setAttribute("stroke-width", strokeWidth.toString());
    if (dashArray)
      line.setAttribute("stroke-dasharray", dashArray);
    return line;
  }
  createText(x, y, content, fill, fontSize) {
    const text = document.createElementNS("http://www.w3.org/2000/svg", "text");
    text.setAttribute("x", x.toString());
    text.setAttribute("y", y.toString());
    text.setAttribute("text-anchor", "middle");
    text.setAttribute("fill", fill);
    text.setAttribute("font-size", fontSize.toString());
    text.textContent = content;
    return text;
  }
};

// src/analyzer.ts
var StrategicAnalyzer = class {
  constructor(graph, checkNoteExists) {
    this.graph = graph;
    this.checkNoteExists = checkNoteExists != null ? checkNoteExists : null;
  }
  analyze(componentIds) {
    const components = [];
    for (const id of componentIds) {
      const node = this.graph.getNode(id);
      if (node == null ? void 0 : node.strategic) {
        components.push({ id, strategic: node.strategic });
      }
    }
    const warnings = this.generateValidationWarnings(components);
    const insights = this.generateStrategicInsights(components);
    const summary = this.generateSummary(components);
    return { warnings, insights, summary };
  }
  generateValidationWarnings(components) {
    const warnings = [];
    for (const { id, strategic } of components) {
      if (strategic.confidence_level === "low") {
        warnings.push({
          type: "low_confidence",
          message: "Component has low confidence rating",
          component_path: id,
          severity: "medium"
        });
      }
      if (!strategic.evidence_sources || strategic.evidence_sources.length === 0) {
        warnings.push({
          type: "missing_evidence",
          message: "Component lacks evidence sources",
          component_path: id,
          severity: "medium"
        });
      } else if (this.checkNoteExists) {
        const missing = this.findMissingEvidenceNotes(strategic.evidence_sources);
        if (missing.length > 0) {
          warnings.push({
            type: "missing_evidence",
            message: `Referenced evidence notes don't exist: ${missing.join(", ")}`,
            component_path: id,
            severity: "low"
          });
        }
      }
      if (strategic.last_validated) {
        const validatedDate = new Date(strategic.last_validated);
        const now = /* @__PURE__ */ new Date();
        const monthsOld = (now.getTime() - validatedDate.getTime()) / (1e3 * 60 * 60 * 24 * 30);
        if (monthsOld > 6) {
          warnings.push({
            type: "outdated_validation",
            message: `Component hasn't been validated in ${Math.floor(monthsOld)} months`,
            component_path: id,
            severity: monthsOld > 12 ? "high" : "medium"
          });
        }
      } else {
        warnings.push({
          type: "outdated_validation",
          message: "Component has no validation date",
          component_path: id,
          severity: "low"
        });
      }
      if (strategic.type && strategic.evolution_stage) {
        const inconsistencies = this.checkEvolutionConsistency(
          strategic.type,
          strategic.evolution_stage
        );
        if (inconsistencies.length > 0) {
          warnings.push({
            type: "evolution_inconsistency",
            message: `Evolution stage may be inconsistent: ${inconsistencies.join(", ")}`,
            component_path: id,
            severity: "low"
          });
        }
      }
    }
    return warnings.sort((a, b) => {
      var _a, _b;
      const severityOrder = { high: 3, medium: 2, low: 1 };
      return ((_a = severityOrder[b.severity]) != null ? _a : 0) - ((_b = severityOrder[a.severity]) != null ? _b : 0);
    });
  }
  checkEvolutionConsistency(type, evolution_stage) {
    const inconsistencies = [];
    const expectations = {
      user_need: ["genesis", "custom"],
      capability: ["custom", "product"],
      component: ["product", "commodity"],
      service: ["product", "commodity"],
      product: ["custom", "product"]
    };
    const expected = expectations[type];
    if (expected && !expected.includes(evolution_stage)) {
      inconsistencies.push(
        `${type} components typically exist in ${expected.join(" or ")} stages`
      );
    }
    return inconsistencies;
  }
  generateStrategicInsights(components) {
    const insights = [];
    const orphaned = this.findOrphanedComponents(components);
    if (orphaned.length > 0) {
      insights.push({
        type: "orphaned_component",
        message: `${orphaned.length} component(s) have no strategic relationships`,
        affected_components: orphaned,
        priority: "medium"
      });
    }
    const criticalPath = this.findCriticalPath(components);
    if (criticalPath.length > 0) {
      insights.push({
        type: "critical_path",
        message: `${criticalPath.length} component(s) are on the critical path`,
        affected_components: criticalPath,
        priority: "high"
      });
    }
    const evolutionGaps = this.findEvolutionGaps(components);
    if (evolutionGaps.length > 0) {
      insights.push({
        type: "evolution_gap",
        message: `Potential evolution gaps detected in ${evolutionGaps.length} areas`,
        affected_components: evolutionGaps,
        priority: "medium"
      });
    }
    const dependencyRisks = this.findDependencyRisks(components);
    if (dependencyRisks.length > 0) {
      insights.push({
        type: "dependency_risk",
        message: `${dependencyRisks.length} component(s) have high dependency risk`,
        affected_components: dependencyRisks,
        priority: "high"
      });
    }
    return insights.sort((a, b) => {
      var _a, _b;
      const priorityOrder = { high: 3, medium: 2, low: 1 };
      return ((_a = priorityOrder[b.priority]) != null ? _a : 0) - ((_b = priorityOrder[a.priority]) != null ? _b : 0);
    });
  }
  findOrphanedComponents(components) {
    const componentIds = new Set(components.map((c) => c.id));
    const connected = /* @__PURE__ */ new Set();
    this.graph.forEachEdge((edge) => {
      if (componentIds.has(edge.source) && componentIds.has(edge.target)) {
        connected.add(edge.source);
        connected.add(edge.target);
      }
    });
    return components.filter((comp) => !connected.has(comp.id)).map((comp) => comp.id);
  }
  findCriticalPath(components) {
    const critical = [];
    const componentIds = new Set(components.map((c) => c.id));
    for (const { id, strategic } of components) {
      if (strategic.strategic_importance === "critical") {
        critical.push(id);
        continue;
      }
      let dependencyCount = 0;
      this.graph.forEachEdge((edge) => {
        if (!componentIds.has(edge.source) || !componentIds.has(edge.target))
          return;
        if (edge.target === id && edge.field === "depends_on") {
          dependencyCount++;
        } else if (edge.source === id && edge.field === "enables") {
          dependencyCount++;
        }
      });
      if (dependencyCount >= 3) {
        critical.push(id);
      }
    }
    return critical;
  }
  /**
   * Find evolution gaps: a more-evolved component depending on a much less-evolved one.
   *
   * In Wardley maps, a "depends_on" edge means the source (note with the field)
   * depends on the target. Normal: user_need (genesis) depends_on component (commodity).
   * Abnormal: commodity depends_on genesis with a gap > 1 stage, suggesting
   * missing intermediate layers.
   *
   * The original breadcrumbs code had this comparison backwards.
   */
  findEvolutionGaps(components) {
    const gaps = [];
    const componentIds = new Set(components.map((c) => c.id));
    const componentMap = new Map(components.map((c) => [c.id, c]));
    const evolutionOrder = ["genesis", "custom", "product", "commodity"];
    this.graph.forEachEdge((edge) => {
      if (!componentIds.has(edge.source) || !componentIds.has(edge.target))
        return;
      if (edge.field !== "depends_on")
        return;
      const sourceComp = componentMap.get(edge.source);
      const targetComp = componentMap.get(edge.target);
      if (!(sourceComp == null ? void 0 : sourceComp.strategic.evolution_stage) || !(targetComp == null ? void 0 : targetComp.strategic.evolution_stage))
        return;
      const sourceIndex = evolutionOrder.indexOf(sourceComp.strategic.evolution_stage);
      const targetIndex = evolutionOrder.indexOf(targetComp.strategic.evolution_stage);
      if (sourceIndex > targetIndex && sourceIndex - targetIndex > 1) {
        gaps.push(edge.source);
      }
    });
    return [...new Set(gaps)];
  }
  findDependencyRisks(components) {
    const risks = [];
    const componentIds = new Set(components.map((c) => c.id));
    const componentMap = new Map(components.map((c) => [c.id, c]));
    this.graph.forEachEdge((edge) => {
      if (!componentIds.has(edge.source) || !componentIds.has(edge.target))
        return;
      if (edge.field !== "depends_on")
        return;
      const targetComp = componentMap.get(edge.target);
      if (!(targetComp == null ? void 0 : targetComp.strategic))
        return;
      let isRisky = false;
      if (targetComp.strategic.confidence_level === "low") {
        isRisky = true;
      }
      if (targetComp.strategic.last_validated) {
        const validatedDate = new Date(targetComp.strategic.last_validated);
        const now = /* @__PURE__ */ new Date();
        const monthsOld = (now.getTime() - validatedDate.getTime()) / (1e3 * 60 * 60 * 24 * 30);
        if (monthsOld > 12) {
          isRisky = true;
        }
      }
      if (isRisky) {
        risks.push(edge.source);
      }
    });
    return [...new Set(risks)];
  }
  findMissingEvidenceNotes(evidenceSources) {
    if (!this.checkNoteExists)
      return [];
    const missing = [];
    for (const source of evidenceSources) {
      const noteMatch = source.match(/\[\[([^\]]+)\]\]/);
      if (noteMatch) {
        const noteName = noteMatch[1];
        if (!this.checkNoteExists(noteName)) {
          missing.push(noteName);
        }
      }
    }
    return missing;
  }
  generateSummary(components) {
    const summary = {
      total_components: components.length,
      by_evolution: {},
      by_importance: {},
      by_confidence: {}
    };
    for (const { strategic } of components) {
      const evolution = strategic.evolution_stage || "unknown";
      summary.by_evolution[evolution] = (summary.by_evolution[evolution] || 0) + 1;
      const importance = strategic.strategic_importance || "unknown";
      summary.by_importance[importance] = (summary.by_importance[importance] || 0) + 1;
      const confidence = strategic.confidence_level || "unknown";
      summary.by_confidence[confidence] = (summary.by_confidence[confidence] || 0) + 1;
    }
    return summary;
  }
};

// src/views/intelligence-panel.ts
var IntelligencePanel = class {
  constructor(container, app, graph, contextManager) {
    this.loading = false;
    this.container = container;
    this.app = app;
    this.graph = graph;
    this.contextManager = contextManager;
  }
  async refresh(scanWarnings) {
    this.loading = true;
    this.container.empty();
    const context = this.contextManager.getCurrentMapContext() || this.contextManager.getDefaultMapContext();
    if (!context) {
      this.renderEmptyState();
      return;
    }
    const checkNoteExists = (name) => {
      const allFiles = this.app.vault.getMarkdownFiles();
      return allFiles.some((f) => f.basename === name);
    };
    const analyzer = new StrategicAnalyzer(this.graph, checkNoteExists);
    const componentIds = this.contextManager.getComponentsForMap(context.id);
    const result = analyzer.analyze(componentIds);
    this.renderPanel(context.name, context.scope, result, scanWarnings != null ? scanWarnings : []);
    this.loading = false;
  }
  renderPanel(contextName, scope, result, scanWarnings) {
    const panel = this.container.createDiv({ cls: "strategic-intelligence-panel" });
    const header = panel.createDiv({ cls: "panel-header" });
    header.createEl("h3", { text: "Strategic Intelligence" });
    const refreshBtn = header.createEl("button", { cls: "refresh-btn", text: "Refresh" });
    refreshBtn.addEventListener("click", () => this.refresh(scanWarnings));
    if (scanWarnings.length > 0) {
      this.renderScanWarnings(panel, scanWarnings);
    }
    const contextInfo = panel.createDiv({ cls: "context-info" });
    contextInfo.createEl("h4", { text: contextName });
    contextInfo.createEl("span", { text: scope, cls: "context-scope" });
    const cards = panel.createDiv({ cls: "summary-cards" });
    this.renderCard(cards, "Components", result.summary.total_components.toString());
    this.renderCard(cards, "Warnings", result.warnings.length.toString(), "critical");
    this.renderCard(cards, "Insights", result.insights.length.toString(), "info");
    if (Object.keys(result.summary.by_evolution).length > 0) {
      this.renderDistribution(panel, result.summary.by_evolution, result.summary.total_components);
    }
    if (result.warnings.length > 0) {
      this.renderWarnings(panel, result.warnings);
    }
    if (result.insights.length > 0) {
      this.renderInsights(panel, result.insights);
    }
  }
  renderCard(parent, title, value, cls) {
    const card = parent.createDiv({ cls: "summary-card" });
    card.createDiv({ cls: "card-title", text: title });
    const valEl = card.createDiv({ cls: "card-value", text: value });
    if (cls)
      valEl.addClass(cls);
  }
  renderDistribution(parent, byEvolution, total) {
    const section = parent.createDiv({ cls: "distribution-section" });
    section.createEl("h5", { text: "Evolution Distribution" });
    const bars = section.createDiv({ cls: "distribution-bars" });
    for (const [stage, count] of Object.entries(byEvolution)) {
      const item = bars.createDiv({ cls: "distribution-item" });
      item.createEl("span", { cls: "stage-name", text: stage });
      const barContainer = item.createDiv({ cls: "bar-container" });
      const bar = barContainer.createDiv({ cls: `bar evolution-${stage}` });
      bar.style.width = `${count / total * 100}%`;
      item.createEl("span", { cls: "count", text: count.toString() });
    }
  }
  renderWarnings(parent, warnings) {
    const section = parent.createDiv({ cls: "warnings-section" });
    section.createEl("h5", { text: "Validation Warnings" });
    const list = section.createDiv({ cls: "items-list" });
    for (const warning of warnings) {
      const item = list.createDiv({ cls: `warning-item severity-${warning.severity}` });
      const itemHeader = item.createDiv({ cls: "item-header" });
      itemHeader.createEl("span", { cls: "severity-icon", text: this.getSeverityIcon(warning.severity) });
      itemHeader.createEl("span", { cls: "item-type", text: this.getWarningLabel(warning.type) });
      item.createDiv({ cls: "item-message", text: warning.message });
      const link = item.createEl("button", {
        cls: "component-link",
        text: this.getDisplayName(warning.component_path)
      });
      link.addEventListener("click", () => this.openComponent(warning.component_path));
    }
  }
  renderInsights(parent, insights) {
    const section = parent.createDiv({ cls: "insights-section" });
    section.createEl("h5", { text: "Strategic Insights" });
    const list = section.createDiv({ cls: "items-list" });
    for (const insight of insights) {
      const item = list.createDiv({ cls: `insight-item priority-${insight.priority}` });
      const itemHeader = item.createDiv({ cls: "item-header" });
      itemHeader.createEl("span", { cls: "priority-icon", text: this.getPriorityIcon(insight.priority) });
      itemHeader.createEl("span", { cls: "item-type", text: this.getInsightLabel(insight.type) });
      item.createDiv({ cls: "item-message", text: insight.message });
      if (insight.affected_components.length > 0) {
        const affected = item.createDiv({ cls: "affected-components" });
        const shown = insight.affected_components.slice(0, 3);
        for (const path of shown) {
          const link = affected.createEl("button", {
            cls: "component-link",
            text: this.getDisplayName(path)
          });
          link.addEventListener("click", () => this.openComponent(path));
        }
        if (insight.affected_components.length > 3) {
          affected.createEl("span", {
            cls: "more-components",
            text: `+${insight.affected_components.length - 3} more`
          });
        }
      }
    }
  }
  renderScanWarnings(parent, scanWarnings) {
    const section = parent.createDiv({ cls: "scan-warnings-section" });
    section.createEl("h5", { text: `Malformed Notes (${scanWarnings.length})` });
    const list = section.createDiv({ cls: "items-list" });
    for (const warning of scanWarnings) {
      const item = list.createDiv({ cls: "warning-item severity-medium" });
      const itemHeader = item.createDiv({ cls: "item-header" });
      itemHeader.createEl("span", { cls: "severity-icon", text: "\u26A0\uFE0F" });
      const link = itemHeader.createEl("button", {
        cls: "component-link",
        text: this.getDisplayName(warning.path)
      });
      link.addEventListener("click", () => this.openComponent(warning.path));
      for (const problem of warning.problems) {
        item.createDiv({ cls: "item-message", text: problem });
      }
    }
  }
  renderEmptyState() {
    const empty = this.container.createDiv({ cls: "empty-state" });
    empty.createEl("p", { text: "No strategic map context available." });
    empty.createEl("p", { text: "Add strategic metadata to your notes to enable analysis." });
  }
  openComponent(path) {
    this.app.workspace.openLinkText(path, "", false);
  }
  getDisplayName(path) {
    var _a;
    return ((_a = path.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) || path;
  }
  getSeverityIcon(severity) {
    const icons = { high: "\u{1F534}", medium: "\u{1F7E1}", low: "\u{1F7E2}" };
    return icons[severity] || "\u26AA";
  }
  getPriorityIcon(priority) {
    const icons = { high: "\u26A1", medium: "\u{1F4CB}", low: "\u{1F4A1}" };
    return icons[priority] || "\u{1F4CC}";
  }
  getWarningLabel(type) {
    const labels = {
      low_confidence: "Low Confidence",
      missing_evidence: "Missing Evidence",
      outdated_validation: "Outdated Validation",
      evolution_inconsistency: "Evolution Inconsistency"
    };
    return labels[type] || type.replace(/_/g, " ");
  }
  getInsightLabel(type) {
    const labels = {
      orphaned_component: "Orphaned Components",
      critical_path: "Critical Path",
      evolution_gap: "Evolution Gap",
      dependency_risk: "Dependency Risk"
    };
    return labels[type] || type.replace(/_/g, " ");
  }
};

// src/views/map-view.ts
var VIEW_TYPE_WARDLEY = "wardley-strategic-map";
var WardleyMapView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.renderer = null;
    this.intelligencePanel = null;
    this.currentContext = null;
    this.showIntelligence = false;
    // DOM refs
    this.selectEl = null;
    this.canvasEl = null;
    this.panelEl = null;
    this.contentEl_ = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_WARDLEY;
  }
  getDisplayText() {
    return "Wardley Map";
  }
  getIcon() {
    return "map";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("wardley-map-container");
    const toolbar = container.createDiv({ cls: "wardley-map-controls" });
    const selectorDiv = toolbar.createDiv({ cls: "map-selector" });
    selectorDiv.createEl("label", { text: "Strategic Map:" });
    this.selectEl = selectorDiv.createEl("select");
    this.selectEl.addEventListener("change", () => this.onContextChange());
    const actionsDiv = toolbar.createDiv({ cls: "map-actions" });
    const intelligenceBtn = actionsDiv.createEl("button", {
      cls: "clickable-icon",
      attr: { "aria-label": "Toggle strategic intelligence panel" }
    });
    intelligenceBtn.innerHTML = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 11H1a1 1 0 0 0-1 1v9a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-9a1 1 0 0 0-1-1Z"/><path d="M22 6a1 1 0 0 0-1-1h-8a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V6Z"/></svg>';
    intelligenceBtn.addEventListener("click", () => this.toggleIntelligence(intelligenceBtn));
    const refreshBtn = actionsDiv.createEl("button", {
      cls: "clickable-icon",
      attr: { "aria-label": "Refresh map" }
    });
    refreshBtn.innerHTML = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M23 4v6h-6M1 20v-6h6"/><path d="M20.49 9A9 9 0 0 0 5.64 5.64L1 10m22 4l-4.64 4.36A9 9 0 0 1 3.51 15"/></svg>';
    refreshBtn.addEventListener("click", () => this.refreshMap());
    const mapInfo = container.createDiv({ cls: "map-info" });
    mapInfo.style.display = "none";
    this.contentEl_ = container.createDiv({ cls: "wardley-content" });
    this.canvasEl = this.contentEl_.createDiv({ cls: "wardley-map-canvas" });
    this.panelEl = this.contentEl_.createDiv({ cls: "intelligence-panel" });
    this.panelEl.style.display = "none";
    this.renderer = new WardleyMapRenderer(
      this.canvasEl,
      this.plugin.graph,
      this.plugin.contextManager,
      this.plugin.settings.visual,
      (path) => this.app.workspace.openLinkText(path, "", false)
    );
    this.intelligencePanel = new IntelligencePanel(
      this.panelEl,
      this.app,
      this.plugin.graph,
      this.plugin.contextManager
    );
    await this.refreshContexts();
    if (this.currentContext) {
      this.renderer.render(this.currentContext.id);
      this.updateMapInfo(container.querySelector(".map-info"));
    }
    this.registerEvent(
      // @ts-ignore: custom event
      this.app.workspace.on("wardley-strategic:graph-updated", () => {
        setTimeout(() => this.refreshMap(), 100);
      })
    );
  }
  async onClose() {
  }
  async refreshContexts() {
    var _a;
    const contexts = await this.plugin.contextManager.detectMapContexts();
    this.currentContext = this.plugin.contextManager.getCurrentMapContext() || this.plugin.contextManager.getDefaultMapContext();
    if (this.selectEl) {
      this.selectEl.empty();
      for (const ctx of contexts) {
        const option = this.selectEl.createEl("option", {
          text: ctx.name,
          value: ctx.id
        });
        if (ctx.id === ((_a = this.currentContext) == null ? void 0 : _a.id)) {
          option.selected = true;
        }
      }
    }
  }
  onContextChange() {
    if (!this.selectEl)
      return;
    const selectedId = this.selectEl.value;
    const contexts = this.plugin.contextManager["cachedContexts"];
    const selected = contexts.find((ctx) => ctx.id === selectedId);
    if (selected) {
      this.currentContext = selected;
      this.plugin.contextManager.setCurrentMapContext(selected);
      if (this.renderer)
        this.renderer.render(selected.id);
      if (this.showIntelligence && this.intelligencePanel) {
        this.intelligencePanel.refresh(this.plugin.scanWarnings);
      }
      const mapInfo = this.containerEl.querySelector(".map-info");
      if (mapInfo)
        this.updateMapInfo(mapInfo);
    }
  }
  async refreshMap() {
    if (this.canvasEl) {
      this.renderer = new WardleyMapRenderer(
        this.canvasEl,
        this.plugin.graph,
        this.plugin.contextManager,
        this.plugin.settings.visual,
        (path) => this.app.workspace.openLinkText(path, "", false)
      );
    }
    if (this.panelEl) {
      this.intelligencePanel = new IntelligencePanel(
        this.panelEl,
        this.app,
        this.plugin.graph,
        this.plugin.contextManager
      );
    }
    await this.refreshContexts();
    if (this.renderer && this.currentContext) {
      this.renderer.render(this.currentContext.id);
    }
    if (this.showIntelligence && this.intelligencePanel) {
      await this.intelligencePanel.refresh(this.plugin.scanWarnings);
    }
    const mapInfo = this.containerEl.querySelector(".map-info");
    if (mapInfo)
      this.updateMapInfo(mapInfo);
  }
  toggleIntelligence(btn) {
    this.showIntelligence = !this.showIntelligence;
    if (this.panelEl) {
      this.panelEl.style.display = this.showIntelligence ? "" : "none";
    }
    if (this.contentEl_) {
      this.contentEl_.toggleClass("split-view", this.showIntelligence);
    }
    btn.toggleClass("active", this.showIntelligence);
    if (this.showIntelligence && this.intelligencePanel) {
      this.intelligencePanel.refresh(this.plugin.scanWarnings);
    }
  }
  updateMapInfo(mapInfo) {
    mapInfo.empty();
    if (!this.currentContext) {
      mapInfo.style.display = "none";
      return;
    }
    mapInfo.style.display = "";
    mapInfo.createEl("h3", { text: this.currentContext.name });
    if (this.currentContext.description) {
      mapInfo.createEl("p", { cls: "map-description", text: this.currentContext.description });
    }
    mapInfo.createEl("span", {
      cls: `map-scope-badge scope-${this.currentContext.scope}`,
      text: this.currentContext.scope
    });
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var DEFAULT_SETTINGS = {
  visual: { ...DEFAULT_VISUAL_SETTINGS }
};
var WardleyStrategicSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, settings, onSave) {
    super(app, null);
    this.settings = settings;
    this.onSave = onSave;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Wardley Strategic Mapping" });
    new import_obsidian4.Setting(containerEl).setName("Font size").setDesc("Font size for component labels").addSlider((slider) => slider.setLimits(8, 16, 1).setValue(this.settings.visual.font_size).setDynamicTooltip().onChange(async (value) => {
      this.settings.visual.font_size = value;
      await this.onSave();
    }));
    new import_obsidian4.Setting(containerEl).setName("Node size").setDesc("Radius of component circles").addSlider((slider) => slider.setLimits(6, 20, 1).setValue(this.settings.visual.node_size).setDynamicTooltip().onChange(async (value) => {
      this.settings.visual.node_size = value;
      await this.onSave();
    }));
    new import_obsidian4.Setting(containerEl).setName("Edge thickness").setDesc("Width of relationship lines").addSlider((slider) => slider.setLimits(1, 5, 0.5).setValue(this.settings.visual.edge_thickness).setDynamicTooltip().onChange(async (value) => {
      this.settings.visual.edge_thickness = value;
      await this.onSave();
    }));
    new import_obsidian4.Setting(containerEl).setName("Component spacing").setDesc("Spacing between overlapping components").addSlider((slider) => slider.setLimits(40, 120, 10).setValue(this.settings.visual.component_spacing).setDynamicTooltip().onChange(async (value) => {
      this.settings.visual.component_spacing = value;
      await this.onSave();
    }));
    new import_obsidian4.Setting(containerEl).setName("Show evolution grid").setDesc("Display vertical grid lines for evolution stages").addToggle((toggle) => toggle.setValue(this.settings.visual.show_evolution_grid).onChange(async (value) => {
      this.settings.visual.show_evolution_grid = value;
      await this.onSave();
    }));
    new import_obsidian4.Setting(containerEl).setName("Show axis labels").setDesc("Display axis labels for Value Chain and Evolution").addToggle((toggle) => toggle.setValue(this.settings.visual.show_axis_labels).onChange(async (value) => {
      this.settings.visual.show_axis_labels = value;
      await this.onSave();
    }));
  }
};

// src/main.ts
var WardleyStrategicPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.graph = new StrategicGraph();
    this.scanWarnings = [];
  }
  async onload() {
    await this.loadSettings();
    this.scanner = new VaultScanner(this.app);
    this.contextManager = new MapContextManager(this.app, this.graph);
    this.registerView(
      VIEW_TYPE_WARDLEY,
      (leaf) => new WardleyMapView(leaf, this)
    );
    this.addCommand({
      id: "open-wardley-map",
      name: "Open Wardley Strategic Map",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "refresh-wardley-graph",
      name: "Refresh strategic graph",
      callback: () => this.refresh()
    });
    this.addSettingTab(
      new WardleyStrategicSettingTab(this.app, this.settings, async () => {
        await this.saveData(this.settings);
      })
    );
    this.app.workspace.onLayoutReady(() => {
      this.refresh();
      this.registerEvent(
        this.app.metadataCache.on("changed", () => {
          this.refresh();
        })
      );
      this.registerEvent(
        this.app.vault.on("rename", () => {
          this.refresh();
        })
      );
      this.registerEvent(
        this.app.vault.on("delete", () => {
          this.refresh();
        })
      );
    });
  }
  onunload() {
  }
  refresh() {
    const { graph, warnings } = this.scanner.scanVault();
    this.graph = graph;
    this.scanWarnings = warnings;
    this.contextManager = new MapContextManager(this.app, this.graph);
    this.app.workspace.trigger("wardley-strategic:graph-updated");
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_WARDLEY);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({ type: VIEW_TYPE_WARDLEY, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
};
